version: "3"

networks:
    public:
        driver: bridge
    internal:
        driver: bridge
        internal: true

volumes:
    mongo_data:
    chronos_cache:
    chronos_log:

services:
    chronos:
        build: ../image/php7.2-apache
        ports:
            - 80:80
        networks:
            - internal
            - public
        env_file: 
            - ./.env
            - ${CHRONOS_PATH}/.env
        volumes:
            - chronos_cache:/var/www/html/chronos/var/cache
            - chronos_log:/var/www/html/chronos/var/log
        depends_on:
            - rabbitmq
            - mongo
            - redis
    
    hermes:
        image: node
        ports:
            - 8080:8080
        networks:
            - internal
            - public
        depends_on:
            - rabbitmq
    
    worker:
        build: ../image/php7.2-alpine
        networks:
            - internal
            - public
        volumes:
            - ../../tools/composer:/composer
        depends_on:
            - rabbitmq
        
    mongo:
        image: mongo
        networks:
            - internal
        volumes:
            - mongo_data:/data/db
    
    rabbitmq:
        image: rabbitmq
        networks:
            - internal

    redis:
        image: redis
        networks:
            - internal

