version: "3"

networks:
    public:
        driver: bridge
    internal:
        driver: bridge
        internal: true

volumes:
    mongo_data:
    chronos_cache:
    chronos_log:

services:
    proxy:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/cert.crt:/etc/nginx/cert.crt:ro
            - ./nginx/cert.key:/etc/nginx/cert.key:ro
        networks:
            - internal
            - public
        depends_on:
            - chronos
    chronos:
        build: ../image/php7.2-apache-dev
        networks:
            - internal
        env_file: 
            - ./.env
            - ${CHRONOS_PATH}/.env
        environment:
            - APP_ENV=1
            - APP_DEBUG=1
        volumes:
            - ../../tools/composer:/composer
            - ${CHRONOS_PATH}:/var/www/html
            - chronos_cache:/var/www/html/var/cache
            - chronos_log:/var/www/html/var/log
        depends_on:
            - rabbitmq
            - mongo
            - redis
    
    hermes:
        image: node
        ports:
            - 8080:8080
        networks:
            - internal
            - public
        depends_on:
            - rabbitmq
    
    worker:
        build: ../image/php7.2-alpine
        networks:
            - internal
            - public
        volumes:
            - ../../tools/composer:/composer
        depends_on:
            - rabbitmq
        
    maildev:
        image: djfarrelly/maildev
        ports:
          - 82:80
        networks:
            - internal
            - public
    
    mongo:
        image: mongo
        networks:
            - internal
        volumes:
            - mongo_data:/data/db
    
    rabbitmq:
        image: rabbitmq
        networks:
            - internal

    redis:
        image: redis
        networks:
            - internal

