version: "3"

networks:
    public:
        driver: bridge
    internal:
        driver: bridge
        internal: true

volumes:
    mongo_data:
    chronos_cache:
    chronos_log:

services:
    chronos:
        build: ../image/php7.2-apache
        ports:
            - 80:80
        networks:
            - internal
            - public
        env_file: ./.env
        environment:
            - APP_ENV=1
            - APP_DEBUG=1
        volumes:
            - ../../tools/composer:/composer
            - ${CHRONOS_PATH}:/var/www/html
            - chronos_cache:/var/www/html/var/cache
            - chronos_log:/var/www/html/var/log
    
    hermes:
        image: node
        ports:
            - 8080:8080
        networks:
            - internal
            - public
    
    worker:
        build: ../image/php7.2-alpine
        networks:
            - internal
            - public
        volumes:
            - ../../tools/composer:/composer
        
    maildev:
        image: djfarrelly/maildev
        ports:
          - 82:80
        networks:
            - internal
            - public
    
    mongo:
        image: mongo
        networks:
            - internal
        volumes:
            - mongo_data:/data/db
    
    rabbitmq:
        image: rabbitmq
        networks:
            - internal

    redis:
        image: redis
        networks:
            - internal
